import { Checklist, Target, Theme } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const hexToRgb = (hex: string): [number, number, number] => {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
};

const getWeightEmoji = (weight: number) => {
  if (weight >= 5) return '🔴 CRITICAL';
  if (weight >= 4) return '🟠 HIGH';
  if (weight >= 3) return '🟡 MEDIUM';
  if (weight >= 2) return '🔵 LOW';
  return '⚪ INFO';
};

const getCategoryEmoji = (category: string) => {
  const cat = category.toLowerCase();
  if (cat.includes('system')) return '💻';
  if (cat.includes('os')) return '🐧';
  if (cat.includes('network')) return '🌐';
  if (cat.includes('cloud')) return '☁️';
  if (cat.includes('software')) return '📦';
  if (cat.includes('access')) return '🔑';
  if (cat.includes('physical')) return '🏗️';
  if (cat.includes('audit')) return '📜';
  return '📁';
};

export const exportChecklistToMarkdown = (checklist: Checklist): string => {
  let md = `# 🛡️ Security Checklist: ${checklist.title}\n\n`;
  md += `> ${checklist.description}\n\n`;
  md += `---\n\n`;
  
  const categories = Array.from(new Set(checklist.items.map(i => i.category)));
  
  categories.forEach(cat => {
    md += `## ${getCategoryEmoji(cat)} ${cat}\n\n`;
    const items = checklist.items.filter(i => i.category === cat);
    items.forEach((item, idx) => {
      md += `### 🔍 ${idx + 1}. ${item.text}\n`;
      md += `**Impact Weight:** ${getWeightEmoji(item.weight)} (${item.weight}/5)\n\n`;
      if (item.description) {
        md += `> 📝 **Detailed Requirements:**\n`;
        md += `> ${item.description.replace(/\n/g, '\n> ')}\n\n`;
      }
      md += `---\n\n`;
    });
  });
  
  md += `_Generated by Robot Security Fleet Manager_\n`;
  return md;
};

export const exportAllChecklistsToMarkdown = (checklists: Checklist[]): string => {
  let md = `# 🛡️ Full Security Checklist\n\n`;
  md += `This document contains all security checklists managed in the Robot Security Fleet Manager.\n\n`;
  md += `**Total Checklists:** ${checklists.length}\n\n`;
  md += `---\n\n`;
  
  checklists.forEach((cl, idx) => {
    md += `## [${idx + 1}] ${cl.title}\n`;
    md += `> ${cl.description}\n\n`;
    
    const categories = Array.from(new Set(cl.items.map(i => i.category)));
    categories.forEach(cat => {
      md += `### ${getCategoryEmoji(cat)} ${cat}\n\n`;
      const items = cl.items.filter(i => i.category === cat);
      items.forEach((item, iIdx) => {
        md += `#### 🔍 ${iIdx + 1}. ${item.text}\n`;
        md += `**Impact Weight:** ${getWeightEmoji(item.weight)} (${item.weight}/5)\n\n`;
        if (item.description) {
          md += `> 📝 **Detailed Requirements:**\n`;
          md += `> ${item.description.replace(/\n/g, '\n> ')}\n\n`;
        }
      });
    });
    md += `\n---\n\n`;
  });
  
  md += `_Generated by Robot Security Fleet Manager_\n`;
  return md;
};

export const downloadMarkdown = (filename: string, content: string) => {
  const element = document.createElement('a');
  const file = new Blob([content], { type: 'text/markdown' });
  element.href = URL.createObjectURL(file);
  element.download = `${filename}.md`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

export const generateChecklistPDF = (checklist: Checklist, theme: Theme) => {
  const doc = new jsPDF();
  const primaryRgb = hexToRgb(theme.primary);
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text('Security Checklist Report', 14, 22);
  
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59); // Slate-800
  doc.text(checklist.title, 14, 32);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(checklist.description, 14, 40, { maxWidth: 180 });

  let currentY = 55;

  const categories = Array.from(new Set(checklist.items.map(i => i.category)));
  
  categories.forEach(cat => {
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text(cat, 14, currentY);
    currentY += 10;

    const items = checklist.items.filter(i => i.category === cat);
    const tableData = items.map((item, idx) => [
      (idx + 1).toString(),
      item.text,
      item.weight.toString(),
      item.description || 'N/A'
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['#', 'Requirement', 'Weight', 'Details']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: primaryRgb },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 60 },
        2: { cellWidth: 20 },
        3: { cellWidth: 90 }
      },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;
  });

  doc.save(`${checklist.title.replace(/\s+/g, '_')}_Checklist.pdf`);
};

export const generateAllChecklistsPDF = (checklists: Checklist[], theme: Theme) => {
  const doc = new jsPDF();
  const primaryRgb = hexToRgb(theme.primary);
  
  // Cover Page
  doc.setFillColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.rect(0, 0, 210, 297, 'F');
  
  doc.setFontSize(32);
  doc.setTextColor(255, 255, 255);
  doc.text('Full Security Checklist', 105, 100, { align: 'center' });
  
  doc.setFontSize(14);
  doc.text(`Total Checklists: ${checklists.length}`, 105, 120, { align: 'center' });
  
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  const timeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}:${String(now.getSeconds()).padStart(2, '0')}`;
  
  doc.setFontSize(10);
  doc.text(`Generated on: ${dateStr} ${timeStr}`, 105, 140, { align: 'center' });
  
  checklists.forEach((cl, clIdx) => {
    doc.addPage();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text(`[${clIdx + 1}] ${cl.title}`, 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(cl.description, 14, 30, { maxWidth: 180 });
    
    let currentY = 45;
    const categories = Array.from(new Set(cl.items.map(i => i.category)));
    
    categories.forEach(cat => {
      if (currentY > 250) {
        doc.addPage();
        currentY = 20;
      }
      
      doc.setFontSize(14);
      doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
      doc.text(cat, 14, currentY);
      currentY += 10;
      
      const items = cl.items.filter(i => i.category === cat);
      const tableData = items.map((item, idx) => [
        (idx + 1).toString(),
        item.text,
        item.weight.toString(),
        item.description || 'N/A'
      ]);
      
      autoTable(doc, {
        startY: currentY,
        head: [['#', 'Requirement', 'Weight', 'Details']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: primaryRgb },
        columnStyles: {
          0: { cellWidth: 10 },
          1: { cellWidth: 60 },
          2: { cellWidth: 20 },
          3: { cellWidth: 90 }
        },
        margin: { left: 14, right: 14 }
      });
      
      currentY = (doc as any).lastAutoTable.finalY + 15;
    });
  });
  
  doc.save(`Full_Security_Checklist.pdf`);
};

export const generateTargetSecurityReport = (target: Target, checklist: Checklist, theme: Theme, aiAnalysis?: any) => {
  const doc = new jsPDF();
  const primaryRgb = hexToRgb(theme.primary);
  const now = new Date();
  const timestamp = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}:${String(now.getSeconds()).padStart(2, '0')}`;
  
  // Fancy Header
  doc.setFillColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('Security Analysis Report', 14, 25);
  
  doc.setFontSize(9);
  doc.text(`Generated: ${timestamp}`, 150, 25);

  // Target Info
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(target.name, 14, 55);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text(`Type: ${target.type}`, 14, 62);
  doc.text(target.description || '', 14, 70, { maxWidth: 180 });

  // Score Section
  const score = 100 - target.riskScore;
  const status = target.riskScore > 70 ? 'CRITICAL' : target.riskScore > 40 ? 'WARNING' : 'SECURE';
  const statusColor = target.riskScore > 70 ? [225, 29, 72] : target.riskScore > 40 ? [217, 119, 6] : [5, 150, 105];

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 80, 196, 80);

  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text('Security Posture Summary', 14, 95);

  doc.setFontSize(48);
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(`${score}%`, 14, 120);
  
  doc.setFontSize(14);
  doc.text(`Status: ${status}`, 60, 115);
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Based on weighted security control verification.', 60, 122);

  // Findings Table
  doc.setFontSize(14);
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text('Detailed Findings', 14, 140);

  const results = target.checklistResults[checklist.id] || {};
  const findingsData = checklist.items.map(item => {
    const res = results[item.id];
    const completed = typeof res === 'boolean' ? res : res?.checked;
    const justification = typeof res === 'object' ? res?.justification : '';
    const status = typeof res === 'object' ? res?.reviewStatus : 'pending';
    
    let resultText = completed ? 'PASSED' : 'FAILED';
    if (!completed && status === 'approved') {
      resultText = 'EXCEPTED (Approved)';
    } else if (!completed && status === 'rejected') {
      resultText = 'FAILED (Rejected)';
    }

    return [
      item.text,
      item.category,
      item.weight.toString(),
      resultText,
      justification || 'N/A'
    ];
  });

  autoTable(doc, {
    startY: 145,
    head: [['Control', 'Category', 'Weight', 'Result', 'Justification']],
    body: findingsData,
    theme: 'grid',
    headStyles: { fillColor: primaryRgb },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30 },
      2: { cellWidth: 20 },
      3: { cellWidth: 30 },
      4: { cellWidth: 50 }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 3) {
        if (data.cell.text[0] === 'PASSED') {
          data.cell.styles.textColor = [5, 150, 105];
          data.cell.styles.fontStyle = 'bold';
        } else if (data.cell.text[0] === 'EXCEPTED (Approved)') {
          data.cell.styles.textColor = primaryRgb;
          data.cell.styles.fontStyle = 'bold';
        } else {
          data.cell.styles.textColor = [225, 29, 72];
          data.cell.styles.fontStyle = 'bold';
        }
      }
    }
  });

  // AI Recommendations if available
  if (aiAnalysis) {
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    if (finalY > 230) doc.addPage();
    
    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('AI-Powered Recommendations', 14, finalY > 230 ? 20 : finalY);
    
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const recs = aiAnalysis.recommendations || [];
    let recY = (finalY > 230 ? 30 : finalY + 10);
    
    recs.forEach((rec: string, i: number) => {
      doc.text(`• ${rec}`, 14, recY, { maxWidth: 180 });
      recY += 7;
    });
  }

  doc.save(`${target.name.replace(/\s+/g, '_')}_Security_Report.pdf`);
};
